version: '3.5'
services:
  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    volumes:
      - ./test/config/prover/initproverdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]

  zkevm-pool-db:
    container_name: zkevm-pool-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command: ["postgres", "-N", "500"]

  zkevm-bridge-db:
    container_name: zkevm-bridge-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    expose:
      - 5435
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: ["postgres", "-N", "500"]

  zkevm-node:
    container_name: zkevm-node
    image: hermeznetwork/zkevm-node:v0.2.4
    ports:
      - 8123:8123
      - 61090:61090
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=zkevm-rpc-db
      - ZKEVM_NODE_ETHERMAN_PRIVATEKEYPATH=/pk/keystore
    volumes:
      - ./test/test.keystore.sequencer:/pk/keystore.sequencer
      - ./test/test.keystore.aggregator:/pk/keystore.aggregator
      - ./test/config/node/config.zkevm.node.toml:/app/config.toml
      - ./test/config/node/genesis.local.json:/app/genesis.json
    command: 
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node approve --network custom --custom-network-file /app/genesis.json --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml --key-store-path /pk/keystore.sequencer --password testonly &&
         /app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"synchronizer,rpc,sequencer,sequence-sender,aggregator,eth-tx-manager,l2gaspricer\""

  zkevm-mock-l1-network:
    container_name: zkevm-local-l1-network
    image: hermeznetwork/geth-zkevm-contracts:v2.0.0-RC1-fork.5-geth1.12.0
    ports:
      - 8545:8545

  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:v2.0.1
    ports:
      - 50051:50051 # Prover
      - 50052:50052 # MockProver
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./test/config/prover/config.prover.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-bridge-service:
    container_name: zkevm-bridge-service
    image: zkevm-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=zkevm-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./test/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.local.toml:/app/config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"

  cdk-validium-mock-l1-network-custom-native-token:
    container_name: zkevm-mock-l1-network
    image: hermeznetwork/geth-cdk-validium-contracts:gas
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"

  cdk-validium-node-custom-native-token:
    container_name: zkevm-node
    image: cdk-validium-node
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - CDK_VALIDIUM_NODE_STATEDB_HOST=zkevm-state-db
      - CDK_VALIDIUM_NODE_POOL_DB_HOST=zkevm-pool-db
      - CDK_VALIDIUM_NODE_AGGREGATOR_SENDER_ADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
    volumes:
      - ./test/test.keystore.sequencer:/pk/sequencer.keystore
      - ./test/test.keystore.aggregator:/pk/aggregator.keystore
      - ./test/config/node/validium.node.toml:/app/config.toml
      - ./test/config/node/custom-native-token.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/cdk-validium-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components eth-tx-manager,sequencer,rpc,synchronizer,sequence-sender,aggregator"
